### ISSUE TITLE
# Toolbar toolbar = (Toolbar)this.findViewById(id.tlbr_acPay);

### ISSUE THREAD

**Issue by Hossein1995** [TurKurT656/HamrahPay#1]
protected void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            this.setContentView(layout.activity_pay);
          #   Toolbar toolbar = (Toolbar)this.findViewById(id.tlbr_acPay);
            toolbar.setBackgroundColor(hamrahPay.getPageTopColor());
            toolbar.setTitleTextColor(hamrahPay.getPageTitleColor());
            this.setSupportActionBar(toolbar);
            if(this.getSupportActionBar() != null) {
                this.getSupportActionBar().setTitle(string.pay);
                this.getSupportActionBar().setHomeButtonEnabled(true);
                this.getSupportActionBar().setDisplayHomeAsUpEnabled(true);
            }

توی کلاس همراه نمیتونه تولبار رو جنریت کنه و این خطا رو میده
java.lang.NoSuchFieldError: No static field tlbr_acPay of type I in class Lir/devage/hamrahpay/R$id;

**Comment by TurKurT656** [comment]
شما دارین یه نسخه دیگه مینویسین؟  چون نوشتن اینا تو کتابخانه ای که نوشتم ضرورتی نداره
به هر حال مشکل اینجاست که باید از کلاس زیر تولبار رو بگیرین:
R.id.tlbr_acPay
