### ISSUE TITLE
مشکل با ایمیل

### ISSUE THREAD

**Issue by maysamrasoli** [TurKurT656/HamrahPay#2]
سلام و خسته نباشید.
بنده از ای پی آی شما استفاده کردم و خیلی راضی هستم.
یوزر موقع خرید ایمیل ثبت میکنه.اگه ایمیل الکی ثبت کنه به چه صورت هست؟
ممنون میشم توضیح بفرمایید

**Comment by TurKurT656** [comment]
سلام
بنده صرفا کتابخونه رو طبق پاسخ های سرور سایت همراه پی نوشتم و هیچ اطلاعی نسبت به این موضوع ندارم، شما میتونین سوال خودتونو از طریق تیکت در سایت همراه پی بپرسین. 

باتشکر
