### ISSUE TITLE
کد برای انتقال به یک صفحه

### ISSUE THREAD

**Issue by ariof** [TurKurT656/HamrahPay#4]
چه کدی داخل صفحه ای که توش میخوایم پرداخت انجام بشه بنویسیم که وقتی پرداخت با موفقیت انجام شد به یه اکتیویتی دیگه ای منتقل بشه؟

**Comment by TurKurT656** [comment]
در قسمت onPaymentSucceed 
اینتنت بسازید و به اکتیویتی مورد نظر منتقل شید.
