### ISSUE TITLE
پروگارد

### ISSUE THREAD

**Issue by elshen321** [TurKurT656/HamrahPay#6]
سلام 
متاسفانه  همراه  پی  با  پروگارد  مشکل  داره  ، آیا  کسی تونسته  تا بحال  حلش  بکنه ؟

**Comment by TurKurT656** [comment]
سلام دوست عزیر،
بنده مدت زیادی شده که روی این کتابخونه کار نکردم و ظاهرا خود شرکت تغییراتی روی کتابخونه اعمال کرده.
بنظرم بهتره سوالتون رو از خود شرکت بپرسید و اونا مشکلتون رو حل کنن
با تشکر
